// apps/vue/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { RouterLink, RouterView } from 'vue-router'
import HelloWorld from './components/HelloWorld.vue'
import { postMessageFlow, postMessageUtils } from '@packages/micro-frontends'

let parentMessage = ref('')

const whitelist = ['http://localhost:5173']
const messageCallback = (event) => {
  const { origin, data } = event

  if (origin === 'http://localhost:5173') {
    return (parentMessage.value = `Received from parent: ${data}`)
  }
}

const { initializePostMessageListener, closePostMessageListener } = postMessageFlow({
  whitelist,
  messageCallback
})

const { messageParent } = postMessageUtils()

onMounted(() => {
  initializePostMessageListener()
})

onUnmounted(() => {
  closePostMessageListener()
})

const callParent = () => {
  messageParent({ message: 'hello', src: 'http://localhost:5173' })
}
</script>

<template>
  <header>
    {{ parentMessage }}
    <button @click="callParent">Call parent</button>
    <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="125" height="125" />

    <div class="wrapper">
      <HelloWorld msg="You did it!" />

      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </nav>
    </div>
  </header>

  <RouterView />
</template>

<style scoped>
header {
  line-height: 1.5;
  max-height: 100vh;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

nav {
  width: 100%;
  font-size: 12px;
  text-align: center;
  margin-top: 2rem;
}

nav a.router-link-exact-active {
  color: var(--color-text);
}

nav a.router-link-exact-active:hover {
  background-color: transparent;
}

nav a {
  display: inline-block;
  padding: 0 1rem;
  border-left: 1px solid var(--color-border);
}

nav a:first-of-type {
  border: 0;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }

  nav {
    text-align: left;
    margin-left: -1rem;
    font-size: 1rem;

    padding: 1rem 0;
    margin-top: 1rem;
  }
}
</style>

// typescript/apps/vite-micro/src/App.tsx
import { useEffect, useState } from "react";
import reactLogo from "~/assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { postMessageFlow, postMessageUtils } from "@packages/micro-frontends";

function App() {
  const [parentMessage, setParentMessage] = useState("");
  const { messageParent } = postMessageUtils();

  useEffect(() => {
    const whitelist = ["http://localhost:5173"];

    const { initializePostMessageListener, closePostMessageListener } = postMessageFlow<string>({
      whitelist,
      messageCallback: (event) => {
        const { origin, data } = event;

        if (origin === "http://localhost:5173") {
          return setParentMessage(data);
        }
      },
    });

    initializePostMessageListener();

    return () => {
      closePostMessageListener();
    };
  }, []);

  const [count, setCount] = useState(0);

  const callParent = () => {
    messageParent({ message: "hello", src: "http://localhost:5173" });
  };

  return (
    <>
      {parentMessage}
      <button onClick={callParent}>Call parent</button>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the Vite and React logos to learn more</p>
    </>
  );
}

export default App;
